#!/usr/bin/sh
# 20. Create a local swarm, the Char virtual machine should be its manager.
docker-machine ssh Char "docker swarm init --advertise-addr $(docker-machine ip Char)"
# To validate, run -> docker node ls
