#!/usr/bin/sh
# 24. Launch a rabbitmq SERVICE that will be named orbital-command. You should
# define a specific user and password for the RabbitMQ service, they can be whatever
# you want. This service will be on the overmind network.
docker service create --name orbital-command --network overmind -e RABBITMQ_DEFAULT_USER=ch3rry -e RABBITMQ_DEFAULT_PASS=c rabbitmq
# To validate, run -> docker inspect orbital-command