#!/usr/bi/sh
# 26. Launch a 42school/engineering-bay service in two replicas and make sure that
# the service works properly (see the documentation provided at hub.docker.com).
# This service will be named engineering-bay and will be on the overmind network.
docker service create -d --network overmind --name engineering-bay --replicas 2 -e OC_USERNAME=ch3rry -e OC_PASSWD=c 42school/engineering-bay
# To  validate, run -> docker service ps engineering-bay
